language: php

matrix:
  include:
    - php: 7.1
      env: BUILD_PHAR=true
#      env: STATIC_ANALYSIS=true BUILD_PHAR=true
#    - php: 7.2
#      env: PHPUNIT_FLAGS="--coverage-clover coverage.xml --testsuite=contrib-rectors"
#    - php: 7.2
#      env: PHPUNIT_FLAGS="--coverage-clover coverage.xml --testsuite=general-rectors"
#    - php: 7.2
#      env: PHPUNIT_FLAGS="--coverage-clover coverage.xml --testsuite=main"

install:
  - composer install

before_script:
  # disable xdebug if not coverage
  - if [[ $PHPUNIT_FLAGS = "" ]]; then phpenv config-rm xdebug.ini; fi

script:
  - vendor/bin/phpunit $PHPUNIT_FLAGS
  # disable xdebug
  - phpenv config-rm xdebug.ini || return 0
  - if [[ $STATIC_ANALYSIS != "" ]]; then composer check-cs; fi
  - if [[ $STATIC_ANALYSIS != "" ]]; then composer phpstan; fi
  # build phar test - 1st group is "build-phar" test step by step; 2nd group is all-together
  - |
    if [[ $BUILD_PHAR != "" ]]; then
      mkdir build
      vendor/bin/php-scoper add-prefix --output-dir=build --force
      composer dump-autoload --working-dir=build --classmap-authoritative --no-dev
      chmod +x build/bin/rector
      build/bin/rector
      composer build-phar
      php rector.phar
      vendor/bin/phpunit --testsuite=phar-build
    fi

after_script:
  # upload coverage to Coveralls.io
  - |
    if [[ $PHPUNIT_FLAGS != "" ]]; then
      wget https://github.com/satooshi/php-coveralls/releases/download/v1.0.1/coveralls.phar
      php coveralls.phar --verbose
    fi

cache:
  directories:
    - $HOME/.composer/cache

notifications:
  email: never
